#5 more fixes for desktop icons, scripts, getting pnpm install straight

diff --git a/tools/thumbdrive/home/bin/startaardvark b/tools/thumbdrive/home/bin/startaardvark
--- a/tools/thumbdrive/home/bin/startaardvark
+++ b/tools/thumbdrive/home/bin/startaardvark
@@ -7,3 +7,8 @@ export NVM_DIR="$HOME/.nvm"
 cd $HOME/workspace/esp32/edger/aardvark
 
 pnpm run serve
+if [ $? -ne 0 ] ; then
+  echo "error starting pnpm"
+  echo "type enter to continue"
+  read ans
+fi
